#
# Create:
# $ conda env create --prefix .sbi_env --file environment.yml
#
# Update:
# $ conda env update --prefix .sbi_env --file environment.yml --prune
#
# Activate:
# $ conda activate ~/path/to/sbi/.sbi_env
#
# Nicer prompt (adds to ~/.condarc):
# $ conda config --set env_prompt '({name}) '
#
name: sbi_env

channels:
  - conda-forge
  - pytorch

dependencies:
  - cudatoolkit
  - jupyter
  - jupyterlab
  - matplotlib
  - notebook
  - pillow
  - pip
  - pip:
    - "pyknos>=0.14.2"
    - "pyro-ppl>=1.3.1"
    - -e ".[dev]"
  - "python >= 3.6.0"
  - "pytorch >= 1.8.0"
  - scikit-learn
  - scipy
