site_name: sbi
site_url: "https://sbi-dev.github.io/sbi/"

nav:
  - Home: index.md
  - Installation: install.md
  - Tutorials and Examples:
      - Introduction:
        - Getting started: tutorial/00_getting_started.md
        - Flexible interface: tutorial/02_flexible_interface.md
        - Amortized inference: tutorial/01_gaussian_amortized.md
        - Implemented algorithms: tutorial/16_implemented_methods.md
      - Advanced:
        - Multi-round inference: tutorial/03_multiround_inference.md
        - Sampling algorithms in sbi: tutorial/11_sampler_interface.md
        - Custom density estimators: tutorial/04_density_estimators.md
        - Learning summary statistics: tutorial/05_embedding_net.md
        - SBI with trial-based data: tutorial/14_iid_data_and_permutation_invariant_embeddings.md
        - Handling invalid simulations: tutorial/08_restriction_estimator.md
        - Crafting summary statistics: tutorial/10_crafting_summary_statistics.md
      - Diagnostics:
        - Posterior predictive checks: tutorial/12_diagnostics_posterior_predictive_check.md
        - Simulation-based calibration: tutorial/13_diagnostics_simulation_based_calibration.md
        - Density plots and MCMC diagnostics with ArviZ: tutorial/15_mcmc_diagnostics_with_arviz.md 
      - Analysis:
        - Conditional distributions: tutorial/07_conditional_distributions.md
        - Posterior sensitivity analysis: tutorial/09_sensitivity_analysis.md
      - Examples:
        - Hodgkin-Huxley example: examples/00_HH_simulator.md
        - Decision making model: examples/01_decision_making_model.md
  - Contributing: 
    - Guide: contribute.md
    - Code of Conduct: code_of_conduct.md
  - API Reference: reference.md
  - FAQ: faq.md
  - Credits: credits.md

repo_name: 'sbi-dev/sbi'
repo_url: http://github.com/sbi-dev/sbi

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: 'static/logo.svg'
  collapse_navigation: False

extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/sbi-dev/sbi'

markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 3
  - markdown_include.include:
      base_path: ../
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            heading_level: 3
  
watch:
  - ../sbi

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - 'static/global.css'
